### ISSUE TITLE
error when compute calcualte_grm using example_data

### ISSUE THREAD

**Issue by zhaoc1** [miriam-goldman/microSLAM#25]
> exp_genedata = read.csv("microSLAM-main/example_data/genepresabs.csv") ### read in example gene data
> exp_metadata = read.csv("microSLAM-main//example_data/exp_metadata.csv") ### read in example metadata
> GRM = calculate_grm(exp_genedata)
Error: lazy-load database '/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/microSLAM/R/microSLAM.rdb' is corrupt
In addition: Warning messages:
1: restarting interrupted promise evaluation 
2: internal error -3 in R_decompress1

**Comment by miriam-goldman** [comment]
I think this is a problem with the installation try restarting your R session! https://github.com/lme4/lme4/issues/407

**Comment by zhaoc1** [comment]
I don't think this is the same issue. Anyway, after you rebuild the package, the error is gone.
